# Generated by Django 3.2.5 on 2021-09-09 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ancien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('prenom', models.CharField(max_length=20)),
                ('ecole', models.IntegerField()),
                ('specialite', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=400)),
                ('contact', models.CharField(max_length=25)),
            ],
        ),
    ]
