# Generated by Django 3.2.5 on 2021-09-09 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anciens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ancien',
            name='promo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ancien',
            name='ecole',
            field=models.CharField(max_length=20),
        ),
    ]
