# Generated by Django 3.2.5 on 2021-09-10 23:03

import anciens.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anciens', '0002_auto_20210909_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ancien',
            name='contact',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='ancien',
            name='description',
            field=models.TextField(max_length=400, validators=[anciens.validators.validate_alpha]),
        ),
        migrations.AlterField(
            model_name='ancien',
            name='ecole',
            field=models.CharField(max_length=20, validators=[anciens.validators.validate_alpha]),
        ),
        migrations.AlterField(
            model_name='ancien',
            name='nom',
            field=models.CharField(max_length=20, validators=[anciens.validators.validate_letters]),
        ),
        migrations.AlterField(
            model_name='ancien',
            name='prenom',
            field=models.CharField(max_length=20, validators=[anciens.validators.validate_letters]),
        ),
        migrations.AlterField(
            model_name='ancien',
            name='promo',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(2020), django.core.validators.MinValueValidator(2010)]),
        ),
        migrations.AlterField(
            model_name='ancien',
            name='specialite',
            field=models.CharField(max_length=30, validators=[anciens.validators.validate_letters]),
        ),
    ]
