# Generated by Django 3.2.5 on 2021-09-13 13:46

import anciens.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anciens', '0003_auto_20210910_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='ancien',
            name='entreprise',
            field=models.CharField(default='', max_length=30, validators=[anciens.validators.validate_alpha]),
        ),
        migrations.AlterField(
            model_name='ancien',
            name='specialite',
            field=models.CharField(max_length=30, validators=[anciens.validators.validate_alpha]),
        ),
    ]
