# Generated by Django 3.2.5 on 2021-09-13 14:14

import anciens.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anciens', '0004_auto_20210913_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='ancien',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ancien',
            name='description',
            field=models.TextField(max_length=2000, validators=[anciens.validators.validate_alpha]),
        ),
    ]
