# Generated by Django 3.2.5 on 2021-09-14 16:46

import anciens.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anciens', '0005_auto_20210913_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ancien',
            name='entreprise',
            field=models.CharField(blank=True, default='', max_length=30, null=True, validators=[anciens.validators.validate_alpha]),
        ),
        migrations.AlterField(
            model_name='ancien',
            name='specialite',
            field=models.CharField(max_length=40, validators=[anciens.validators.validate_alpha]),
        ),
    ]
