# Generated by Django 3.2.7 on 2021-09-16 14:54

import anciens.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anciens', '0007_alter_ancien_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ancien',
            name='entreprise',
            field=models.CharField(default='', max_length=30, validators=[anciens.validators.validate_alpha]),
        ),
        migrations.AlterField(
            model_name='ancien',
            name='specialite',
            field=models.CharField(max_length=30, validators=[anciens.validators.validate_alpha]),
        ),
        migrations.AlterField(
            model_name='ancien',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
