# Generated by Django 3.2.7 on 2021-11-19 19:29

import anciens.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anciens', '0008_auto_20210916_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ancien',
            name='entreprise',
            field=models.CharField(blank=True, default='', max_length=30, validators=[anciens.validators.validate_alpha]),
        ),
        migrations.AlterField(
            model_name='ancien',
            name='promo',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(2023), django.core.validators.MinValueValidator(2000)]),
        ),
        migrations.AlterField(
            model_name='ancien',
            name='specialite',
            field=models.CharField(max_length=40, validators=[anciens.validators.validate_alpha]),
        ),
    ]
